name: fps_counter
description: "A simple package to show the current FPS of your Flutter app."
version: 1.0.0+2
repository: https://github.com/SaltySpaghetti/fps_counter

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0